config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "checkout/shipping"
  post "checkout/apply_shipping"
  post "stripe_webhook/listener"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: %i[index show]
  resources :categories, only: %i[index]
  resources :cart, only: %i[create destroy index]
  resources :orders, only: %i[index show create]
  resources :customers, only: %i[show new create]

  # stripe routes
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  # get 'products/show'
  root to: "products#index"
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    # take in a params[:id] and that prodoct id to the session shopping cart
    logger.debug("adding #{params[:quantity]} #{params[:id]} to the shopping cart")
    id = params[:id].to_i
    quantity = params[:quantity].to_i
    product = Product.find(id)
    # ensure that the id passed is valid.
    if product && product.valid?
      session[:shopping_cart][id.to_s] = quantity
      puts "\n\n***************************************************************************************
      \n\nID is: #{id}\n QUANTITY IS: #{quantity} \nCART IS: #{session[:shopping_cart].inspect}\n\n\n
      *************************************************************************\n\n"
      flash[:notice] = "✔ Added #{product.name} to the cart" unless params[:hide_flash] == "true"

    else
      flash[:notice] = "❌ Error adding item to the cart" unless params[:hide_flash] == "true"
    end
    redirect_to request.referer
  end

  def destroy
    # take in a params[:id] and remove that prodooct id to the session shopping cart
    logger.debug("removing #{params[:id]} from the shopping cart")
    id = params[:id].to_i
    product = Product.find(id)
    # ensure that the id passed is valid.
    if product && product.valid?
      session[:shopping_cart].delete(id.to_s) # removes the id from the array
      flash[:notice] = "✔ Removed #{product.name} from cart" unless params[:hide_flash] == "true"
    else
      flash[:notice] = "❌ Error removing item from cart"
    end
    redirect_to request.referer
  end

  def index
    @cart_items = cart_items
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart_item.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <% if cart_item[:product].image_med.present? %>
          <%= image_tag cart_item[:product].image_med, class: 'img-thumbnail float-left' %>
        <% else %>
          <%= image_tag "No_Image_Available.jpg", class: 'img-thumbnail float-left' %>
        <% end%>
      </div>
      <div class="col-md-9">
        <h5 class="card-title"><%= link_to cart_item[:product].name, cart_item[:product]%></h5>
        <p class="card-text"><strong>Our low price: </strong><%= number_to_currency(cart_item[:product].price.to_d / 100) %></p>
        <p class="card-text"><%= cart_item[:product].description%></p>
        <p class="card-text"><strong>Category: </strong><%= cart_item[:product].category.name %></p>
        <%# update cart section %>
        <div class="">
          <div class="d-lg-flex justify-content-between">
            <%= form_with url: cart_index_path, method: :post, class: "" do |form| %>
              <div class="">
                <%= hidden_field_tag(:id, cart_item[:product].id)%>
                <%= hidden_field_tag(:hide_flash, true )%>
                <div class="input-group mb-3" style="width: 15em;">
                  <%= form.number_field :quantity, in: 1..999, class: "form-control", value: cart_item[:quantity] %>
                  <div class="input-group-append">
                    <%= button_tag 'Update Quantity', class: "btn btn-secondary" %>
                  </div>
                </div>
              </div>
            <%end%>
            <div class="">
              <%= form_with url: cart_path(cart_item[:product]), method: :delete do |form| %>
                <%= hidden_field_tag(:hide_flash, true )%>
                <%= button_tag 'Remove From Cart', class: "btn btn-secondary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cart/index.html.erb
<div class="container">
  <h1>Your Cart</h1>
  <% if @cart_items.size == 0 %>
    <p>Your cart is empty! <%= link_to "Continue shopping", products_path %>.</p>
  <% else %>
    <div class="row">
      <div class="col-lg-9">
        <%= render partial: 'cart_item',
                  collection: @cart_items %>
      </div>
      <div class="col-lg-3">
        <%= button_to checkout_shipping_path, method: :get, class: "btn btn-success btn-lg w-100" do %>
          Checkout
        <% end%>
      </div>
    </div>
  <% end %>
  </div>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>