config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "checkout/shipping"
  post "checkout/apply_shipping"
  post "stripe_webhook/listener"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: %i[index show]
  resources :categories, only: %i[index]
  resources :cart, only: %i[create destroy index]
  resources :orders, only: %i[index show create]
  resources :customers, only: %i[show new create]

  # stripe routes
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  # get 'products/show'
  root to: "products#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products
  has_many :products, through: :order_products
  accepts_nested_attributes_for :products, allow_destroy: true

  validates :customer, :total, :status, presence: true
  validate :has_a_tax
  # validates :stripe_session, uniqueness: true

  def has_a_tax
    fields = %i[PST GST HST]

    errors.add(:base, "Please specify a tax") unless fields.any? { |field| send(field).present? }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    # where user can view past orders
    if user_signed_in?
      customer = current_user.customer

      unless customer.nil?
        @orders = Order.where(customer: customer).where.not(status: "unsubmitted").order(created_at: :desc)
      end
    else
      # redirect to login page
      redirect_to new_user_session_path
    end
  end

  def show
    @order = Order.find(params[:id])
    puts "\n\n\n\n\n\nORDER CUSTOMER ID #{@order.customer.id}"
    puts "SESSION CUSTOMER ID #{session[:customer_id]}\n\n\n\n\n"
    if (@order.customer.id == session[:customer_id]) || (user_signed_in? && @order.customer.id == current_user.customer.id)
      @orderProducts = @order.order_products
      @total = @order.total
      @pst = @order.PST
      @gst = @order.GST
      @hst = @order.HST
      @subtotal = @total - @pst - @gst - @hst
      @preOrder = @order.status == "unsubmitted"
      @status = @order.status
    end
  end

  def create
    # get and save shipping details
    inputs = params[:customer]
    province = if inputs[:province_id].nil?
                 nil
               else
                 Province.find(inputs[:province_id])
               end
    cust = Customer.find_or_create_by(
      first_name:    inputs[:first_name],
      middle_name:   inputs[:middle_name],
      last_name:     inputs[:last_name],
      address_line1: inputs[:address_line1],
      address_line2: inputs[:address_line2],
      country:       inputs[:country],
      province:      province,
      city:          inputs[:city],
      postal:        inputs[:postal],
      email:         inputs[:email],
      phone:         inputs[:phone]
    )

    if cust.valid?
      # set the current customer to this customr
      session[:customer_id] = cust.id

      # valid customer data, so create order summary
      @items = cart_items
      @customer = Customer.find(cust.id) unless session[:customer_id].nil?

      if @items.nil? || @items.size == 0
        flash[:notice] = "❌ Must have at least one item to prepare order."
        redirect_to request.referer
        return
      elsif @customer.nil?
        flash[:notice] = "❌ Error fetching shipping details for order."
        redirect_to request.referer
        return
      end

      # where the total/taxes will be stored
      subtotal = 0
      pst = 0
      gst = 0
      hst = 0

      if @customer.valid?
        order = Order.create(
          customer: @customer,
          total:    0,
          status:   "incomplete",
          PST:      pst,
          GST:      gst,
          HST:      hst
        )

        # add products to the order and calculate taxes
        @items.each do |item|
          product = item[:product]
          quantity = item[:quantity]
          OrderProduct.create(
            order:    order,
            product:  product,
            price:    product.price,
            quantity: quantity
          )

          # Add to total and taxes.
          subtotal += product.price * quantity
          unless @customer.province.PST.nil?
            pst += product.price * quantity * @customer.province.PST
          end
          unless @customer.province.GST.nil?
            gst += product.price * quantity * @customer.province.GST
          end
          unless @customer.province.HST.nil?
            hst += product.price * quantity * @customer.province.HST
          end
        end

        # calculate the full total
        total = subtotal + pst + gst + hst

        # Update the order with the calculated totals
        order.update(
          total:  total,
          status: "unsubmitted",
          PST:    pst,
          GST:    gst,
          HST:    hst
        )

        # store order in session so we can add stripe session to it shortly
        session[:order_id] = order.id

        redirect_to(order) if order.valid?
      end
    else
      # ivalid shipping details, will have to find way to display errors.
      puts cust.errors.inspect
      redirect_to request.referer
    end
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_invoice_item.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <% if orderProduct.product.image_med.present? %>
          <%= image_tag orderProduct.product.image_med, class: 'img-thumbnail float-left' %>
        <% else %>
          <%= image_tag "No_Image_Available.jpg", class: 'img-thumbnail float-left' %>
        <% end%>
      </div>
      <div class="col-md-9">
        <h5 class="card-title"><%= link_to orderProduct.product.name, orderProduct.product%></h5>
        <p class="card-text"><strong>price: </strong><%= number_to_currency(orderProduct.price.to_d / 100) %></p>
        <p class="card-text"><strong>quantity: </strong><%= orderProduct.quantity %></p>
      </div>
    </div>
  </div>
</div>

app/views/orders/create.html.erb
<div class="container">
  <p>Error occurred while preparing order.</p>
</div>

app/views/orders/index.html.erb
<div class="container">
  <h1>Your Orders</h1>
  <div class="card">
    <div class="card-body">
      <% if @orders.size == 0 %>
        <p>You do not have any existing orders, <%= link_to "make some", products_path %>!</p>
      <% else %>
        <% @orders.each do |order| %>
            <div class="card">
              <div class="card-body">
                <%= link_to(order, class: "text-dark text-decoration-none") do %>
                  <div>
                    <div class="row">
                      <div class="col-lg-9">
                        <p class="card-text mb-1">Order #: <%= order.stripe_session %></p>
                      </div>
                      <div class="col-lg">
                        <p class="card-text text-lg-right">Order Status: <%= order.status %></p>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg">
                        <p class="card-text">Order Total: <%= number_to_currency(order.total.to_d / 100) %></p>
                      </div>
                      <div class="col-lg">
                        <p class="card-text text-lg-right">Order Date: <%= order.created_at.strftime("%b %d, %Y") %></p>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h1>
  <% if @preOrder %>
    Order Summary
  <% else %>
    Order Invoice
  <% end %>
  </h1>
  <div class="card">
    <div class="card-head">
      <div class="container pt-3">
        <p><strong>Sub-Total:</strong> <%= number_to_currency(@subtotal.to_d / 100) %></p>
        <% unless @gst.nil? || @gst == 0 %>
          <p><strong>GST:</strong> <%= number_to_currency(@gst.to_d / 100) %></p>
        <% end %>
        <% unless @pst.nil? || @pst == 0 %>
          <p><strong>PST:</strong> <%= number_to_currency(@pst.to_d / 100) %></p>
        <% end %>
        <% unless @hst.nil? || @hst == 0 %>
          <p><strong>HST:</strong> <%= number_to_currency(@hst.to_d / 100) %></p>
        <% end %>
        <p><strong>Total:</strong> <%= number_to_currency(@total.to_d / 100) %></p>
        <% if @preOrder %>
          <%= button_to checkout_create_path, method: :create, remote: true, class: "btn btn-primary" do %>
            Proceed to Payment
          <% end %>
        <% else %>
          <p><strong>Status:</strong> <%= @status %></p>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <%= render partial: 'invoice_item',
            collection: @orderProducts,
            as: :orderProduct %>
    </div>

  </div>
</div>