config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "checkout/shipping"
  post "checkout/apply_shipping"
  post "stripe_webhook/listener"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: %i[index show]
  resources :categories, only: %i[index]
  resources :cart, only: %i[create destroy index]
  resources :orders, only: %i[index show create]
  resources :customers, only: %i[show new create]

  # stripe routes
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  # get 'products/show'
  root to: "products#index"
end

app/views/common/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <span class="navbar-brand">PC Components®</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" type="button" id="productsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Products
          </a>
          <div class="dropdown-menu" aria-labelledby="productsDropdown">
            <%= link_to "All Products", products_path, class: "dropdown-item" %>
            <% categories.each do |category| %>
              <%= link_to category.name, "#{products_path}?category=#{category.id}", class: "dropdown-item" %>
            <% end %>
          </div>
        </div>
        <li class="nav-item <%= 'active' if controller_name == 'contact'%>">
          <%= link_to "Contact", 'contact', class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if controller_name == 'about'%>">
          <%= link_to "About", 'about', class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if controller_name == 'sessions' && action_name  == 'destroy'%>">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'orders' && action_name  == 'index' %>">
            <%= link_to "Orders", orders_path, method: :get, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item <%= 'active' if controller_name == 'sessions' && action_name  == 'new'%>">
            <%= link_to "Sign In", user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'registrations' && action_name  == 'new'%>">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item <%= 'active' if controller_name == 'cart'%>">
          <%# <%= link_to "Cart <span class=\"badge badge-light\">#{cart.size}</span>", cart_index_path, class: "nav-link" %>
          <%= link_to cart_index_path, class: "nav-link" do %>
            Cart <span class="badge badge-primary"><%= cart.size %></span>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>